# Generated by Django 3.1.2 on 2020-10-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_calendar_app', '0004_auto_20201007_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='notification_calendar_app.Tag'),
        ),
    ]
