# Generated by Django 3.1.2 on 2020-10-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_calendar_app', '0006_auto_20201014_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Noname', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='noname', max_length=100),
            preserve_default=False,
        ),
    ]
