# Generated by Django 3.1.2 on 2020-10-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_calendar_app', '0009_auto_20201016_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App_User',
            new_name='Profile',
        ),
    ]
