# Generated by Django 3.1.2 on 2020-10-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_calendar_app', '0011_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
