# Generated by Django 3.1.2 on 2020-10-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_calendar_app', '0012_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
